on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: release all os -- no code signing

jobs:
  create-release:
    runs-on: ubuntu-18.04 # Updated to a more recent Ubuntu version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4
        with:
          fetch-depth: 0 # Ensure full history for release notes

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2 # Updated to a more maintained release action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Deskreen Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          generate_release_notes: true # Added for automatic release notes

  release:
    name: Deskreen Release
    runs-on: ${{ matrix.os }}
    needs: create-release # Ensure release is created before building

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04 # Updated to match create-release and improve cache compatibility
            artifact_name: 'release/{*.AppImage,*.rpm,*.deb,*.yml}'
          - os: windows-2022 # Updated to newer Windows version
            artifact_name: 'release/{*.msi,*.exe,*.blockmap,*.yml}'
          - os: macos-14 # Updated to newer macOS version
            artifact_name: 'release/{*.dmg,*.blockmap,*.yml}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '20' # Updated to a more recent LTS version
          cache: 'yarn' # Enable built-in Yarn caching

      - name: yarn install in ./app/client
        run: |
          cd ./app/client
          yarn install --frozen-lockfile

      - name: yarn install in ./
        run: yarn install --frozen-lockfile

      - name: yarn install in ./app
        run: |
          cd ./app
          yarn install --frozen-lockfile

      - name: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn build

      - name: yarn lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn lint

      - name: yarn tsc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn tsc

      - name: yarn package-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn package-ci

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2 # Updated to a more maintained release action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ matrix.artifact_name }}
          draft: true
